RpcException: Added correct error RpcException error thrown from all the catch of properties crud, project crud services and tested that. Location service catch throw is pending and add location,addCity,addLocal,addCoordinate which is the sub_function from add and update Property and Project API is not added any error formats and developer module is completly untouched on error handling